#!/opt/homebrew/bin/php
<?php

echo "Running tests.. " . PHP_EOL;
exec('./vendor/bin/pest', $testResults, $returnCode);
if ($returnCode !== 0) {
    foreach($testResults as $testResult) echo $testResult . PHP_EOL;
    echo "Opps! Something went wrong. Can not push changes until tests are OK." . PHP_EOL;
    exit(1);
}

// Show summary (last 3 line)
foreach (array_slice($testResults, -3, 3) as $testResult) echo $testResult . PHP_EOL;
exit(0);